## Error for 38_RandomForest_GoldenFeatures_SelectedFeatures

All features are droppped! Your data looks like random data.
Traceback (most recent call last):
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/base_automl.py", line 1078, in _fit
    trained = self.train_model(params)
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/base_automl.py", line 365, in train_model
    mf.train(results_path, model_subpath)
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/model_framework.py", line 184, in train
    X_train, y_train, sample_weight = self.preprocessings[
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/preprocessing/preprocessing.py", line 288, in fit_and_transform
    raise AutoMLException(
supervised.exceptions.AutoMLException: All features are droppped! Your data looks like random data.


Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

## Error for 28_LightGBM_SelectedFeatures

All features are droppped! Your data looks like random data.
Traceback (most recent call last):
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/base_automl.py", line 1078, in _fit
    trained = self.train_model(params)
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/base_automl.py", line 365, in train_model
    mf.train(results_path, model_subpath)
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/model_framework.py", line 184, in train
    X_train, y_train, sample_weight = self.preprocessings[
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/preprocessing/preprocessing.py", line 288, in fit_and_transform
    raise AutoMLException(
supervised.exceptions.AutoMLException: All features are droppped! Your data looks like random data.


Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

## Error for 15_Xgboost_SelectedFeatures

All features are droppped! Your data looks like random data.
Traceback (most recent call last):
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/base_automl.py", line 1078, in _fit
    trained = self.train_model(params)
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/base_automl.py", line 365, in train_model
    mf.train(results_path, model_subpath)
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/model_framework.py", line 184, in train
    X_train, y_train, sample_weight = self.preprocessings[
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/preprocessing/preprocessing.py", line 288, in fit_and_transform
    raise AutoMLException(
supervised.exceptions.AutoMLException: All features are droppped! Your data looks like random data.


Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

## Error for 10_Default_ExtraTrees_SelectedFeatures

All features are droppped! Your data looks like random data.
Traceback (most recent call last):
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/base_automl.py", line 1078, in _fit
    trained = self.train_model(params)
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/base_automl.py", line 365, in train_model
    mf.train(results_path, model_subpath)
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/model_framework.py", line 184, in train
    X_train, y_train, sample_weight = self.preprocessings[
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/preprocessing/preprocessing.py", line 288, in fit_and_transform
    raise AutoMLException(
supervised.exceptions.AutoMLException: All features are droppped! Your data looks like random data.


Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

## Error for 29_CatBoost_SelectedFeatures

All features are droppped! Your data looks like random data.
Traceback (most recent call last):
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/base_automl.py", line 1078, in _fit
    trained = self.train_model(params)
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/base_automl.py", line 365, in train_model
    mf.train(results_path, model_subpath)
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/model_framework.py", line 184, in train
    X_train, y_train, sample_weight = self.preprocessings[
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/preprocessing/preprocessing.py", line 288, in fit_and_transform
    raise AutoMLException(
supervised.exceptions.AutoMLException: All features are droppped! Your data looks like random data.


Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

## Error for 59_NeuralNetwork_SelectedFeatures

All features are droppped! Your data looks like random data.
Traceback (most recent call last):
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/base_automl.py", line 1078, in _fit
    trained = self.train_model(params)
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/base_automl.py", line 365, in train_model
    mf.train(results_path, model_subpath)
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/model_framework.py", line 184, in train
    X_train, y_train, sample_weight = self.preprocessings[
  File "/home/comp/anaconda3/envs/for_mljar/lib/python3.9/site-packages/supervised/preprocessing/preprocessing.py", line 288, in fit_and_transform
    raise AutoMLException(
supervised.exceptions.AutoMLException: All features are droppped! Your data looks like random data.


Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

